- block:
  - name: Build uriel image and push it to DockerHub
    docker_image:
      source: build
      force_source: yes
      name: judgels/uriel
      push: yes
      build:
        path: "{{ playbook_dir }}/../../../judgels-backends/uriel/uriel-dist"
        args:
          VCS_REF: "{{ lookup('env', 'GITHUB_SHA') }}"
