- block:
  - name: Build uriel image and push it to Docker Package
    docker_image:
      path: "{{ playbook_dir }}/../../../judgels-backends/uriel/uriel-dist"
      name: docker.pkg.github.com/ia-toki/judgels/uriel
      force: yes
      push: yes
      buildargs:
        VCS_REF: "{{ lookup('env', 'TRAVIS_COMMIT') }}"
