- block:
  - name: Build uriel image and push it to DockerHub
    docker_image:
      path: "{{ playbook_dir }}/../../../judgels-backends/uriel/uriel-dist"
      name: judgels/uriel
      force: yes
      push: yes

  - name: Tag uriel latest version
    docker_image:
      name: judgels/uriel:latest
      repository: "judgels/uriel:{{ judgels_version }}"
      force: yes
      pull: no
      push: yes
      state: present
    when: judgels_version is defined
