---
- block:
  - name: "Generate docker-entrypoint.sh"
    template:
      src: "docker-entrypoint.sh.j2"
      dest: "{{ playbook_dir }}/../../dockerfiles/nginx/docker-entrypoint.sh"

  - name: "Generate jophiel nginx template"
    template:
      src: "jophiel.j2"
      dest: "{{ playbook_dir }}/../../dockerfiles/nginx/jophiel"

  - name: "Build jophiel-nginx image and push it to dockerhub"
    docker_image:
      path: "{{ playbook_dir }}/../../dockerfiles/nginx"
      name: "judgels/jophiel-nginx"
      tag: "latest"
      push: yes

  tags:
    - "nginx-build"
