- block:
    - name: Create judgels server container mount volume
      file:
        path: "{{ item }}"
        state: directory
        mode: 0777
      with_items:
        - /judgels/server/var
        - /judgels/server/var/conf

    - name: Allow judgels server traffic through the firewall
      ufw:
        rule: allow
        to_port: '9101'
        proto: tcp
        comment: judgels server
