---
- block:
  - name: "Create var dir on hosts to mount"
    file:
      path: "{{ item }}"
      recurse: "yes"
      state: "directory"
      mode: "0777"
    with_items:
      - /judgels/jophiel/var
      - /judgels/jophiel/var/conf

  - name: "Generate jophiel configurations"
    template:
      src: "jophiel.yml.j2"
      dest: "/judgels/jophiel/var/conf/jophiel.yml"

  - name: "Pull jophiel image"
    docker_image:
      name: "judgels/jophiel"
      force: "yes"

  - name: "Create a jophiel container"
    docker_container:
      name: "jophiel"
      image: "judgels/jophiel"
      restart: "yes"
      network_mode: "host"
      ports:
        - "{{ jophiel_port }}:{{ jophiel_port }}"
      volumes:
        - "/judgels/jophiel/var:/judgels/jophiel/var"

  tags:
    - "jophiel-deploy"
