- block:
  - name: Prune docker artifacts
    raw: docker system prune -f && docker rmi -f $(docker images -q --filter "dangling=true") || true

  - name: Create jophiel container mount volume
    file:
      path: "{{ item }}"
      recurse: yes
      state: directory
      mode: "0777"
    with_items:
      - /judgels/jophiel/var
      - /judgels/jophiel/var/conf

  - name: Generate jophiel config
    template:
      src: jophiel.yml.j2
      dest: /judgels/jophiel/var/conf/jophiel.yml

  - name: Pull jophiel image
    docker_image:
      name: judgels/jophiel
      force: yes

  - name: Run a jophiel container
    docker_container:
      name: jophiel
      image: judgels/jophiel
      restart: yes
      network_mode: host
      volumes:
        - "/judgels/jophiel/var:/judgels/jophiel/var"
  tags:
    - jophiel-deploy
