language: java

git:
  depth: false

addons:
  ssh_known_hosts: test3.ia-toki.org

before_install:
  - openssl aes-256-cbc -K $encrypted_bd46b89c8fce_key -iv $encrypted_bd46b89c8fce_iv -in jophiel-dist/deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - git clone -q git@gitlab.com:ia-toki/tlx-staging.git
  - sudo apt-add-repository ppa:ansible/ansible -y
  - sudo apt-get -q update
  - sudo apt-get install -y ansible docker.io python-pip
  - sudo pip install docker-py

script:
  - "./gradlew clean distTar"
  - mkdir -p jophiel-dist/dockerfiles/jophiel/build/distributions
  - tar -xf jophiel-dist/build/distributions/jophiel-* -C jophiel-dist/dockerfiles/jophiel/build/distributions

deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch: test
