language: java

git:
  depth: false

addons:
  ssh_known_hosts: test3.ia-toki.org

env:
  global:
    - secure: Diw2z2elX9jgv1SaTJVrCY7I/X4t55e7v6+20TqB4NtcsJdlB4x3Eg4jnWEC/GKo0VGDNG70rmNHxXwQcZ7UJp2Rle/cMD+BX1QcxxjDWTz7kLPFdMp7ijQR8CHKCoN/asc/oSyhmRrgcJN4YcisYoCkTbJpxcNUD5QkvCIvNNbtgwki9GbyQuDz8InFkyhNr6MDzSxgVo0pCg2Nm/RkwyaTNEwv2RY7ovg1b+8pXpvXEFKOf8wPzM6VrIKpB4ooVvdQf+Her9ccqqSDe0WF3ot9JQ7usgQtRYCJV6EbkkCIHb9pILoZGmbLyPG9LCcLgwGhUzFFwhIt3A4KOZYPEsmb9YOrOVB+kFngNTjD6+lwQkum/xP0HJp6fEEraq+vJzESHUrlgWga99XPvkpLiCOtVaibbi3F0xL9enjYRHfF0xvS7HwmaeF+GHHlF8mKZcq63HvH1d8gnuwKU7Xzw3J8pETFVGYV+WrvDE3nLIFxoMKuiptJi3oBsNOvJ3IdBm9t4CTBUVHqiQbIWrRF/DthuMdPxh8vNq43doON/An15n7ZUp6vcNqXk1XzEzX8jqu5Un83xzi6j31JeCbcRV/yfuO3P7E4qyeepYb3TCz0eIsmbW/UEJUGe+DXPgnYtG94FcNnGaFNV6rEgNP2cZD3MgiJ0R8FEtXmrKEp2+U=
    - secure: iqYRUDdecxM+Fhd/Mkra/V3jnwz5t5QXT2pMOCT1Um3yIU2gOJNY4mrI5UXJ5ftk4PObrgFo6zsn63BisJ+k2hkpgybWEtGOoNltN9FNgz0HOq2AwXYw9ZM748MiK/M92txaZ/jrxBowvTPGFOVjYCCXT43T8JTYToLE3c0dT5a/8u5PHDMEzAZYggHGk2JQxnZKOrPDDQpt5JVoLt2liL0FHoGa74BJwa8Y/7o4n0aZTScmKV2SjSef2wRV7eLhRbwvEEUKSjz4xUoJKynwndz59IBVceJesJ68oSUXPZQUWsnQNVRwkxZPOmBUwtyOvs9X7MwToBEC5X9NDMFmokCHOIEnOkndjxl/SYAMgbIB/y7p+ecLGN0idJwkcuLRmN5pthi6P7T/bHscfOHfPNMk8tSHeLgaYHLtUA0OLzw/lJc8r92v6WXPu+uSx02ldNtcrbXDcswLbyQzN2lUBtDuf5/OzHhkqVcNkNs8NE5I4vsU62sqm72SYXDY53lK+k6+/eqAI2TpSD/+lv5IgCuOR0oLU2/ib7tRRg3vs08QOvMhSkOtMvaEUJGadIEcPlninuQKYtcei2sOuHMiyr0XytN4Jr2dazeSy8A82z6bC0qD+afAND7PiwyWXZejP49p3are8KnDWVaKVfGFJ2jKufen5AyIlFRGPbUHk4w=
    - secure: DpjP0XcIrRBLtDPnRltlq7DD/571KE5uATE4A3GoEFgfMK6dj4OVGqfxXPzXHCVPtGBRurMMfHpo+Z45kR8eHJSGYvGJnvSdZ5thF+kQ0H5F4NLca2mye27TN7rZeOeSlmTOASqzoZCC7xDEs1y/lr35I82CebOakivlsmeBCZf0mrE3FNl/oK+W4tYhaNZE0+77XyKpPaq6967bHiQFUasmvfEXL0gB08f33oMVZa+r6S24YAk0LJyJgGdXiCtIXdqQ+8Zm1nyYf85uH3+hFnwonzXP24yTrq1e5rACj0R+2iJTtdPEtf/h5/OHI/R6NbRUMFRKo42z4wvUdCZaPQ4p8Nregf1euGk+ODkHe7+MX5KNqCFN+UlNYMXBxQYj/wfG52wljqzyxKpisjZ+79WrEpcTwRkvOfUAtySvpi3JaHAHJnetQ7tQXjioI3aVzJ//2Uyjh1zmFgydJis1ZxbgS5O+UgvPLBU5VReWpZZ8cbXji9sRrfOrIQCsUJvY4lYUKk//kYMcdxeTVvWmZJ1MnCk4Mtq9MG2H8IA0UXg80i1C2tXqEElKhGO48XytkdkCWT+CCMcylwjEEbrahIk0nZQf11cLLcYDs1olkh9nD4Ddm6kvVHNQG3BzLJKQL1Vd5GoJKw4hZzPL05/qN/1ToiQy3oD9UcFqx90rGTA=

before_install:
  - openssl aes-256-cbc -K $encrypted_bd46b89c8fce_key -iv $encrypted_bd46b89c8fce_iv -in jophiel-dist/deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - sudo apt-add-repository ppa:ansible/ansible -y
  - sudo apt-get -qq update
  - sudo apt-get install -y ansible docker.io python-pip
  - sudo pip install docker-py

script:
  - "./gradlew clean distTar"
  - mkdir -p jophiel-dist/dockerfiles/jophiel/build/distributions
  - tar -xf jophiel-dist/build/distributions/jophiel-* -C jophiel-dist/dockerfiles/jophiel/build/distributions

deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch: test
