language: java

git:
  depth: false

addons:
  ssh_known_hosts: test3.ia-toki.org

after_success:
  - jophiel-dist/scripts/build_docker_artifact.sh

before_deploy:
  - openssl aes-256-cbc -K $encrypted_bd46b89c8fce_key -iv $encrypted_bd46b89c8fce_iv -in jophiel-dist/deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - git clone -q git@gitlab.com:ia-toki/tlx-staging.git
  - sudo apt-add-repository ppa:ansible/ansible -y
  - sudo apt-get -q update
  - sudo apt-get install -y ansible docker.io python-pip
  - sudo pip install docker-py

deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch: tlx-staging
