sudo: required

language: java
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper

services:
  - docker

git:
  depth: false

before_script:
  - pip install --user ansible==2.5.5 docker

script: python3 scripts/ci.py check | bash

before_deploy:
  - openssl aes-256-cbc -K $encrypted_46d3e052da1d_key -iv $encrypted_46d3e052da1d_iv -in deployment/deployment_rsa.enc -out /tmp/deployment_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deployment_rsa
  - ssh-add /tmp/deployment_rsa
  - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
  - git clone --depth=1 -q "git@gitlab.com:${deployment_repo}.git" deployment-repo

deploy:
  skip_cleanup: true
  provider: script
  script: python3 scripts/ci.py deploy | bash
  on:
    branch: master
