language: java

git:
  depth: false

addons:
  ssh_known_hosts: test3.ia-toki.org

env:
  - secure: "bIwRKK7lI9vX/Hf2Vq8F7DWNiItHCjZXvTlMXJAjWC4YYx5fRSvBEmOAqCWAPGGKaEyB7UG/kQrTsc5YI53UpKnUdXA7X8e2GK7+lsmLL61+EN0hh4UkfMpjod5eIuXKEr+3vke36oFW8bw6smoMHlE1uYrZvxVT2/oNQsgJ2zyeoHkVZcB3uizF/gk3r65AmdjwI9nn7iEYKGJX1VuqifRMerzNfXonmb8KfuWWy1b+N11L8aFnyK6C5jvC9i0vXTh6jyma6FVLEPsMjR2uopM96SPgixtd3vzBgEifauAIN2GpcNB/Ym8fCoNDzCoiPpLmVN7Jj6Mt/jO6WE4s04HY/b+RopXKje8YAE+aWhaCPj7sIAARjYoStf6I/g3dhOBnTJW7eXpN/ei/dsCXf2Ve/l4TKc3dwXiwX6EEns+XeDDZdBBQyapPJuhMEd9KugbAcedzZhmJ5cRwImnilgCK18+e/iDjz+aa17DtsaGa7mzoFQ148DnkeMqELqzpGd4vwbo/soyjmAxk2P93sJDz453E1/UbAzeDhpsZhssAgF0tDgg/oERK0jp1zEn+rEplhRi4U4+bt4k7WW8Ixlxz8r68MY5udhSR3fHou71ho9ShHcHTX6FxwTd0+QBzKta7TggLAaOzzGfBHI6bDnhExcmnya/kwXN2qiT33EU="

before_install:
  - openssl aes-256-cbc -K $encrypted_bd46b89c8fce_key -iv $encrypted_bd46b89c8fce_iv -in jophiel-dist/deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - sudo apt-add-repository ppa:ansible/ansible -y
  - sudo apt-get -qq update
  - sudo apt-get install -y ansible docker.io python-pip
  - sudo pip install docker-py

script:
  - "./gradlew clean distTar"
  - mkdir -p jophiel-dist/dockerfiles/jophiel/build/distributions
  - tar -xf jophiel-dist/build/distributions/jophiel-* -C jophiel-dist/dockerfiles/jophiel/build/distributions

deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch: test
