language: java

git:
  depth: false

before_deploy:
  - openssl aes-256-cbc -K $encrypted_c5dcd7b22ecb_key -iv $encrypted_c5dcd7b22ecb_iv -in uriel-dist/deployment_rsa.enc -out /tmp/deployment_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deployment_rsa
  - ssh-add /tmp/deployment_rsa
  - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
  - git clone --depth=1 -q "git@gitlab.com:${deployment_repo}.git" deployment
  - git clone --depth=1 -q "https://github.com/judgels-dev/judgels"
  - sudo apt-add-repository ppa:ansible/ansible -y
  - sudo apt-get -q update
  - sudo apt-get install -y ansible docker.io python-pip
  - sudo pip install docker-py

deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
