- block:
  - name: Create frontgate container mount volume
    file:
      path: "{{ item }}"
      recurse: yes
      state: directory
      mode: "0755"
    with_items:
      - /judgels/frontgate/letsencrypt
      - /judgels/frontgate/sites

  - name: Generate nginx site
    template:
      src: default.conf.j2
      dest: /judgels/frontgate/sites/default.conf

  - name: Pull nginx-certbot image
    docker_image:
      name: judgels/nginx-certbot
      force: yes

  - name: Create a nginx-certbot container
    docker_container:
      name: nginx-certbot
      image: judgels/nginx-certbot
      command: nginx
      restart: yes
      network_mode: host
      volumes:
        - /judgels/frontgate/letsencrypt:/etc/letsencrypt
        - /judgels/frontgate/sites:/etc/nginx/conf.d
      env:
        CERTBOT_EMAIL: "{{ letsencrypt_email }}"

  tags:
    - frontgate-deploy
