---
- block:
  - name: "Create letsencrypt dir on hosts to mount"
    file:
      path: "/judgels/jophiel/letsencrypt"
      recurse: "yes"
      state: "directory"
      mode: "0755"

  - name: "Pull jophiel-nginx image"
    docker_image:
      name: "judgels/jophiel-nginx"
      force: "yes"

  - name: "Create a nginx container"
    docker_container:
      name: "jophiel-nginx"
      image: "judgels/jophiel-nginx"
      restart: "yes"
      network_mode: "host"
      ports:
        - "80:80"
        - "443:43"
      volumes:
        - "/judgels/jophiel/letsencrypt:/etc/letsencrypt"

  tags:
    - "nginx-deploy"
