judgels_name: Judgels
judgels_slogan: Programming Contest System
judgels_title: <h1>Welcome to Judgels</h1>
judgels_description: <h2>This is a programming contest system.</h2>
judgels_scheme: https

judgels_client_url: judgels.com
judgels_server_api_url: api.judgels.com
judgels_server_admin_url: admin.judgels.com

judgels_server_xmx: 1g
judgels_grader_xmx: 1g

###################################################################################################

letsencrypt_email: xxx@yyy.com

###################################################################################################

db_root_home: /root
db_root_password: xxx
db_host: localhost
db_username: judgels
db_password: xxx
db_options: "?useSSL=false"

###################################################################################################

jophiel_superadminCreator_initialPassword: xxx
jophiel_session_maxConcurrentSessionsPerUser: -1
jophiel_session_disableLogout: false

###################################################################################################

gabriel_grading_numWorkerThreads: 2

###################################################################################################

rabbitmq_host: localhost
rabbitmq_username: judgels
rabbitmq_password: xxx
