- block:
  - name: Pull phpymyadmin image
    docker_image:
      name: phpmyadmin/phpmyadmin:4.8.5

  - name: Run a phpmyadmin container
    docker_container:
      name: phpmyadmin
      image: phpmyadmin/phpmyadmin:4.8.5
      restart: yes
      log_driver: json-file
      log_options:
        max-size: 256m
        max-file: 2
      ports:
        - '8080:80'
      env:
        PMA_HOST: 172.17.0.1
