- block:
  - name: Create jerahmeel container mount volume
    file:
      path: "{{ item }}"
      state: directory
      mode: "0777"
    with_items:
      - /judgels/jerahmeel/var
      - /judgels/jerahmeel/var/conf
      - /judgels/jerahmeel/var/data

  - name: Generate jerahmeel config
    template:
      src: "{{ playbook_dir }}/../conf/jerahmeel.yml.j2"
      dest: /judgels/jerahmeel/var/conf/jerahmeel.yml
      mode: '0644'

  - name: Generate jerahmeel launcher config
    template:
      src: "{{ playbook_dir }}/../conf/jerahmeel-launcher.yml.j2"
      dest: /judgels/jerahmeel/var/conf/launcher-custom.yml
      mode: '0644'

  - name: Pull jerahmeel image
    docker_image:
      name: ghcr.io/ia-toki/judgels/jerahmeel
      tag: 1.0
      source: pull
      force_source: yes

  - name: Run a jerahmeel container
    docker_container:
      name: jerahmeel
      image: ghcr.io/ia-toki/judgels/jerahmeel:1.0
      restart: yes
      restart_policy: always
      log_driver: json-file
      log_options:
        max-size: 256m
        max-file: "2"
      network_mode: host
      volumes:
        - "/judgels/jerahmeel/var:/judgels/jerahmeel/var"

  - name: Allow jerahmeel traffic through the firewall
    ufw:
      rule: allow
      to_port: "9005"
      proto: tcp
      comment: judgels jerahmeel
