- block:
    - name: Generate judgels grader config
      template:
        src: "{{ playbook_dir }}/../conf/judgels-grader.yml.j2"
        dest: /judgels/grader/var/conf/judgels-grader.yml
        mode: '0600'
      tags: config
      register: judgels_grader_config

    - name: Pull judgels grader image
      docker_image:
        name: ghcr.io/ia-toki/judgels/grader
        tag: "{{ judgels_version | default('latest', true) }}"
        source: pull
        force_source: "{{ judgels_version | default('latest', true) == 'latest' }}"
      tags: config

    - name: Run a judgels grader container
      docker_container:
        name: judgels-grader
        image: "ghcr.io/ia-toki/judgels/grader:{{ judgels_version | default('latest', true) }}"
        privileged: yes
        restart: "{{ judgels_grader_config.changed }}"
        restart_policy: always
        log_driver: json-file
        log_options:
          max-size: 256m
          max-file: "2"
        network_mode: host
        volumes:
          - "/judgels/grader/var:/judgels/grader/var"
          - "/judgels/server/var:/judgels/server/var"
        env:
          JAVA_OPTS: "-Xmx{{ judgels_grader_xmx }}"
          JUDGELS_GRADER_APP_OPTS: "-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/judgels/grader/var/log"
      tags: config
