- block:
    - name: Build jerahmeel image and push it to DockerHub
      docker_image:
        path: "{{ playbook_dir }}/../../../judgels-backends/jerahmeel/jerahmeel-dist"
        name: judgels/jerahmeel
        force: yes
        push: yes
        buildargs:
          VCS_REF: "{{ lookup('env', 'GITHUB_SHA') }}"
