- block:
    - name: Build jerahmeel image and push it to GitHub container registry
      docker_image:
        source: build
        force_source: yes
        name: ghcr.io/ia-toki/judgels/jerahmeel
        push: yes
        build:
          path: "{{ playbook_dir }}/../../../judgels-backends/jerahmeel/jerahmeel-dist"
          args:
            VCS_REF: "{{ lookup('env', 'GITHUB_SHA') }}"
