- block:
    - name: Build jophiel image and push it to DockerHub
      docker_image:
        source: build
        force_source: yes
        name: judgels/jophiel
        push: yes
        build:
          path: "{{ playbook_dir }}/../../../judgels-backends/jophiel/jophiel-dist"
          args:
            VCS_REF: "{{ lookup('env', 'GITHUB_SHA') }}"
