- block:
  - name: Pull rabbitmq image
    docker_image:
      name: rabbitmq:3.7.8-management-alpine

  - name: Run a rabbitmq container
    docker_container:
      name: rabbitmq
      image: rabbitmq:3.7.8-management-alpine
      restart: yes
      restart_policy: always
      log_driver: json-file
      log_options:
        max-size: 256m
        max-file: "2"
      network_mode: host
      env:
        RABBITMQ_DEFAULT_USER: "{{ rabbitmq_mgmt_username }}"
        RABBITMQ_DEFAULT_PASS: "{{ rabbitmq_mgmt_password }}"

  - name: Allow RabbitMQ management traffic through the firewall
    ufw:
      rule: allow
      to_port: 15672
      proto: tcp
      comment: RabbitMQ management
