- block:
  - name: Pull rabbitmq image
    docker_image:
      name: rabbitmq:3.7.8-management-alpine

  - name: Run a rabbitmq container
    docker_container:
      name: rabbitmq
      image: rabbitmq:3.7.8-management-alpine
      restart: yes
      network_mode: host
      env:
        RABBITMQ_DEFAULT_USER: "{{ rabbitmq_mgmt_username }}"
        RABBITMQ_DEFAULT_PASS: "{{ rabbitmq_mgmt_password }}"
  tags:
    - rabbitmq-deploy
