- hosts: nginx
  gather_facts: false
  roles:
    - name: Setup nginx
      role: nginx-certbot-deploy
      vars:
        domains:
          - name: judgels-api
            fqdn: "{{ judgels_api_url }}"
            config_template: "{{ playbook_dir }}/../conf/nginx-judgels-api.conf.j2"
          - name: sandalphon
            fqdn: "{{ sandalphon_url }}"
            config_template: "{{ playbook_dir }}/../conf/nginx-sandalphon.conf.j2"
          - name: raphael
            fqdn: "{{ raphael_url }}"
            config_template: "{{ playbook_dir }}/../conf/nginx-raphael.conf.j2"
          - name: rabbitmq-mgmt
            fqdn: "{{ rabbitmq_mgmt_url }}"
            config_template: "{{ playbook_dir }}/../conf/nginx-rabbitmq-mgmt.conf.j2"
