- hosts: all
  gather_facts: false
  roles:
    - name: python-install
    - name: docker-install
    - name: ufw-install

- hosts: core
  gather_facts: false
  roles:
    - name: judgels-server-provision
    - name: judgels-client-provision

- hosts: grader
  gather_facts: false
  roles:
    - name: judgels-grader-provision
