- block:
  - name: Build raphael image and push it to DockerHub
    docker_image:
      path: "{{ playbook_dir }}/../../../judgels-frontends/raphael/dist"
      name: judgels/raphael
      force: yes
      push: yes

  - name: Tag raphael latest version
    docker_image:
      name: judgels/raphael:latest
      repository: "judgels/raphael:{{ judgels_version }}"
      force: yes
      pull: no
      push: yes
      state: present
    when: judgels_version is defined
