- block:
  - name: Generate jerahmeel config
    template:
      src: "{{ playbook_dir }}/../conf/jerahmeel.conf.j2"
      dest: /judgels/jerahmeel/var/conf/jerahmeel.conf

  - name: Restart jerahmeel
    docker_container:
      name: jerahmeel
      restart: yes
