- block:
  - name: Build gabriel image and push it to Docker Package
    docker_image:
      path: "{{ playbook_dir }}/../../../judgels-backends/gabriel/gabriel-dist"
      name: docker.pkg.github.com/ia-toki/judgels/gabriel
      force: yes
      push: yes
      buildargs:
        VCS_REF: "{{ lookup('env', 'TRAVIS_COMMIT') }}"
