- block:
    - name: Generate judgels server config
      template:
        src: "{{ playbook_dir }}/../conf/judgels-server.yml.j2"
        dest: /judgels/server/var/conf/judgels-server.yml
        mode: '0644'
      tags: config
      register: judgels_server_config

    - name: Pull judgels server image
      docker_image:
        name: ghcr.io/ia-toki/judgels/server
        tag: "{{ judgels_version | default('latest', true) }}"
        source: pull
        force_source: "{{ judgels_version | default('latest', true) == 'latest' }}"
      tags: config

    - name: Run a judgels server container
      docker_container:
        name: judgels-server
        image: "ghcr.io/ia-toki/judgels/server:{{ judgels_version | default('latest', true) }}"
        restart: "{{ judgels_server_config.changed }}"
        restart_policy: always
        log_driver: json-file
        log_options:
          max-size: 256m
          max-file: "2"
        network_mode: host
        volumes:
          - "/judgels/server/var:/judgels/server/var"
        env:
          JAVA_OPTS: "-Xmx{{ judgels_server_xmx }}"
          JUDGELS_SERVER_APP_OPTS: "-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/judgels/server/var/log"
      tags: config

    - name: Set ownership on /judgels/server to that of the container's var/log's and permission to 0*00
      block:
        - name: Get var/log file attributes
          stat:
            path: /judgels/server/var/log
          register: var_log_stat

        - name: Set destination ownership
          file:
            path: /judgels/server
            owner: "{{ var_log_stat.stat.uid }}"
            group: "{{ var_log_stat.stat.gid }}"
            mode: 'g-r,g-w,g-x,o-r,o-w,o-x'
            recurse: true
