- block:
  - name: Create uriel container mount volume
    file:
      path: "{{ item }}"
      state: directory
      mode: "0777"
    with_items:
      - /judgels/uriel/var
      - /judgels/uriel/var/conf

  - name: Generate uriel config
    template:
      src: "{{ playbook_dir }}/../conf/uriel.yml.j2"
      dest: /judgels/uriel/var/conf/uriel.yml
      mode: '0644'

  - name: Pull uriel image
    docker_image:
      name: ghcr.io/ia-toki/judgels/uriel
      tag: 1.0
      source: pull
      force_source: yes

  - name: Run a uriel container to do db migration
    docker_container:
      name: uriel-migrate
      image: ghcr.io/ia-toki/judgels/uriel:1.0
      restart: yes
      network_mode: host
      volumes:
        - "/judgels/uriel/var:/judgels/uriel/var"
      command: dbMigrate
      env:
        JAVA_OPTS: '-Dliquibase.databaseChangeLogTableName=uriel_DATABASECHANGELOG -Dliquibase.databaseChangeLogLockTableName=uriel_DATABASECHANGELOGLOCK'
