- block:
  - name: Create uriel container mount volume
    file:
      path: "{{ item }}"
      state: directory
      mode: "0777"
    with_items:
      - /judgels/uriel/var
      - /judgels/uriel/var/conf

  - name: Generate uriel config
    template:
      src: "{{ playbook_dir }}/../conf/uriel.yml.j2"
      dest: /judgels/uriel/var/conf/uriel.yml

  - name: Pull uriel image
    docker_image:
      name: docker.pkg.github.com/ia-toki/judgels/uriel
      tag: "{{ judgels_version | default('latest', true) }}"
      force: yes

  - name: Run a uriel container to do db migration
    docker_container:
      name: uriel-migrate
      image: "docker.pkg.github.com/ia-toki/judgels/uriel:{{ judgels_version | default('latest', true) }}"
      restart: yes
      network_mode: host
      volumes:
        - "/judgels/uriel/var:/judgels/uriel/var"
      command: dbMigrate
