- block:
  - name: Build sandalphon image and push it to DockerHub
    docker_image:
      path: "{{ playbook_dir }}/../../../judgels-backends/judgels-play/sandalphon"
      name: judgels/sandalphon
      force: yes
      push: yes
      buildargs:
        VCS_REF: "{{ lookup('env', 'GITHUB_SHA') }}"
