- block:
  - name: Build sandalphon image and push it to DockerHub
    docker_image:
      source: build
      force_source: yes
      name: judgels/sandalphon
      push: yes
      build:
        path: "{{ playbook_dir }}/../../../judgels-backends/sandalphon/sandalphon-app"
        args:
          VCS_REF: "{{ lookup('env', 'GITHUB_SHA') }}"
