- block:
  - name: Install cgroup
    apt:
      name: cgroup-tools
      state: present
      install_recommends: no

  - name: Run isolate recommendations # https://github.com/ioi/isolate/blob/master/isolate-check-environment
    copy:
      dest: /etc/rc.local
      mode: 0755
      content: |
        #!/bin/bash

        echo 0 > /proc/sys/kernel/randomize_va_space
        echo never > /sys/kernel/mm/transparent_hugepage/enabled
        echo never > /sys/kernel/mm/transparent_hugepage/defrag
        echo 0 > /sys/kernel/mm/transparent_hugepage/khugepaged/defrag
