- block:
  - name: Build sealtiel image and push it to DockerHub
    docker_image:
      path: "{{ playbook_dir }}/../../../judgels-backends/sealtiel/sealtiel-dist"
      name: judgels/sealtiel
      force: yes
      push: yes

  - name: Tag sealtiel latest version
    docker_image:
      name: judgels/sealtiel:latest
      repository: "judgels/sealtiel:{{ judgels_version }}"
      force: yes
      pull: no
      push: yes
      state: present
    when: judgels_version is defined
