- block:
  - name: Build sealtiel image and push it to DockerHub
    docker_image:
      source: build
      force_source: yes
      name: judgels/sealtiel
      push: yes
      build:
        path: "{{ playbook_dir }}/../../../judgels-backends/sealtiel/sealtiel-dist"
        args:
          VCS_REF: "{{ lookup('env', 'GITHUB_SHA') }}"
