- block:
    - name: Create judgels client container mount volume
      file:
        path: "{{ item }}"
        state: directory
        mode: "0777"
      with_items:
        - /judgels/client/var
        - /judgels/client/var/conf

    - name: Generate judgels client config
      template:
        src: "{{ playbook_dir }}/../conf/judgels-client.js.j2"
        dest: /judgels/client/var/conf/judgels-client.js
        mode: '0644'
      tags: config
      register: judgels_client_config

    - name: Pull judgels client image
      when: judgels_client_config.changed
      docker_image:
        name: ghcr.io/ia-toki/judgels/client
        tag: "{{ judgels_version | default('latest', true) }}"
        source: pull
        force_source: yes
      tags: config

    - name: Run a judgels client container
      docker_container:
        name: judgels-client
        image: "ghcr.io/ia-toki/judgels/client:{{ judgels_version | default('latest', true) }}"
        restart: "{{ judgels_client_config.changed }}"
        restart_policy: always
        log_driver: json-file
        log_options:
          max-size: 256m
          max-file: "2"
        ports:
          - "5000:5000"
        volumes:
          - "/judgels/client/var:/judgels/client/var"
      tags: config

    - name: Allow judgels client traffic through the firewall
      ufw:
        rule: allow
        to_port: "5000"
        proto: tcp
        comment: judgels client
