- block:
    - name: Install docker
      pip:
        name: docker

    - name: Downgrade requests # https://github.com/docker/docker-py/issues/3113 
      pip: 
        name: requests
        version: 2.28.1

    - name: Install docker.io
      apt:
        name: docker.io
        state: present
